"""empty message

Revision ID: 70ad15c7c640
Revises: 8966873448fc
Create Date: 2023-12-29 13:56:03.191994

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '70ad15c7c640'
down_revision = '8966873448fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_email_constraint', 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_email_constraint', 'users', type_='unique')
    # ### end Alembic commands ###
