"""empty message

Revision ID: 79ae791dd2c0
Revises: 70ad15c7c640
Create Date: 2023-12-29 14:00:52.773261

"""
from alembic import op
import sqlalchemy as sa

import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = '79ae791dd2c0'
down_revision = '70ad15c7c640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_score', sa.Column('good_subjects', sa.String(length=256), nullable=False))
    op.drop_column('user_score', 'high_subjects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_score', sa.Column('high_subjects', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('user_score', 'good_subjects')
    # ### end Alembic commands ###
